# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Maxkon Weather Station
version: "1.0.0"
slug: maxkonweatherstation
description: Weather station integration for Maxkon device
url: "https://github.com/aronbardsley/weatherstation/edit/main/maxkonweatherstation"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
schema:
  message: "str?"
